#! /bin/sh

bspc -r "*"

# pgrep -x sxhkd > /dev/null || sxhkd &

# Set keybindings
[ -n "$(pgrep -x sxhkd)"] && killall sxhkd
sxhkd & 

# Start compositor
picom -b --config ~/.config/picom.conf 

# Keyboard Layout
setxkbmap -model logitech_base -layout br -variant abnt2 &



# Brightness and Light Filter app: Redshft
# killall redshift && killall redshift-gtk
# redshift-gtk -c ~/.config/redshift.conf &

# Notifications Dunst
killall dunst
dunst &

# run the xrandr command if an external monitor is connected to the
# laptop. This must be exectured before the polybar commando, so that
# polybar can set the two separate bars properly.
if [[ -x ~/bin/dual_monitor_bspwm ]];then 
    ~/bin/dual_monitor_bspwm 
fi

# Wallpaper
nitrogen --restore &

# Status Bar.
~/bin/polybar/launch-polybar


# ======================== BSPWM ==========================#
bspc monitor VGA-0 -d I II III IV V
bspc monitor DVI-D-0 -d VI VII VIII 

# bspc config focus_follows_pointer true

bspc config border_width         2
bspc config normal_border_color  "#282c34"
#bspc config bottom_padding	 0
bspc config top-padding		 0
bspc config window_gap       0 

bspc config pointer_modifier    mod4
bspc config pointer_action1     move
bspc config pointer_action2     resize_side
bspc config pointer_action3     resize_corner

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop=I follow=on focus=on 
# bspc rule -a Spotify desktop='^2'
bspc config external_rules_command ~/bin/bspwm/external-spotify-rule
# bspc rule -a Joplin desktop=IV follow=off
# bspc rule -a gammy state=floating
# bspc rule -a kitty -o desktop=III


# ================== Start-up applications =================== #

# Brightness and Gamma app: Gammy
gammy & 

# Screenshot app: Flameshot
flameshot &



